auth.sendCode:
    authorizations: [service]
auth.signIn:
    authorizations: [service]
auth.signUp:
    authorizations: [service]
apps.get:
    authorizations: [service, user]
users.get:
    authorizations: [user]
